version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 16
        commands:
            - echo Installing source NPM dependencies...
            - npm install -g @angular/cli
            - npm install -f
    build:
        commands:
            - echo Build started on `date`
            - npm run build
            - echo Build completed...
    post_build:
        commands:
            - echo build process finished, we should uplload to S3 now
            - cd dist/$oauth2_angular
            - ls -la
            - aws s3 sync . s3://oauth2-web --delete
artifacts:
    files:
        - "**/*"
    discard-paths: yes
    base-directory: dist