version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 16
        commands:
            - echo Installing source NPM dependencies...
            - npm install -g @angular/cli
            - npm install -f
    build:
        commands:
            - echo Build started on `date`
            - npm run build
            - echo Build completed...
    post_build:
        commands:
            - echo Pre-Build started on `date`
            - aws s3 cp ./dist/oauth2_angular s3://oauth2-web --recursive --acl public-read
            - echo Pre-Build completed on `date`
artifacts:
    files:
        - dist/oauth2_angular/**/*
    discard-paths: yes